[G2M] Horizontal Bar text value fix
EQWorks/chart-system pull request #186
Opened 2022-09-20 18:26 UTC by kc-leung

fixes #181 

- Fixed plotly horizontal bar text value cut-off

![Screen Shot 2022-09-20 at 2 08 36 PM](https://user-images.githubusercontent.com/46459367/191332316-1ab7bbf1-e296-450b-860c-daa03c1fec25.png)

How about making the text value to be inside the bar when it is too small? Or reducing the font-size?

![Screen Shot 2022-09-20 at 2 09 06 PM](https://user-images.githubusercontent.com/46459367/191332400-3551c1dd-2b16-4de7-895e-a30bf9ad54d7.png)

2022-09-20 18:34 UTC, woozyking approved these changes

2022-09-20 18:45 UTC, geoerika requested changes
@kc-leung thank you so much for this. Is it too much to ask to fix the pyramid chart as well for the same problem?
![Screen Shot 2022-09-20 at 2 45 06 PM](https://user-images.githubusercontent.com/41120953/191339382-99cf58e7-f9e8-4ac3-a820-e2a93a0825a2.png)

2022-09-20 18:49 UTC, kc-leung commented
> @kc-leung thank you so much for this. Is it too much to ask to fix the pyramid chart as well for the same problem? ![Screen Shot 2022-09-20 at 2 45 06 PM](https://user-images.githubusercontent.com/41120953/191339382-99cf58e7-f9e8-4ac3-a820-e2a93a0825a2.png)

yea sure I will take a look

2022-09-20 19:09 UTC, Hamaad102 commented
I'm not sure if this ticket encompasses all instances of text being cut off but I also see it happening on the Plotly Horizontal Stacked

![Screenshot 2022-09-20 150019](https://user-images.githubusercontent.com/18343242/191343512-7e665041-ba85-4694-bb0d-8e14387bb2b1.png)

2022-09-20 20:02 UTC, geoerika commented
@kc-leung if you can't think of a better solution for now, this would do for our present Cox use case. But, it has to be further investigated. If you don't have time now, we can pick it up later:
I changed the values in the storybook for the lower bars to 1400 on each side and we have text cut as well.
![Screen Shot 2022-09-20 at 3 59 31 PM](https://user-images.githubusercontent.com/41120953/191353285-e534027b-674f-4760-96f6-fd71f6fd5034.png)

2022-09-20 20:06 UTC, geoerika commented
@kc-leung don't know how this compares to your solution, maybe it helps: https://community.plotly.com/t/text-is-cut-off-in-plotly-horizontal-bar-chart/47233

2022-09-20 20:09 UTC, kc-leung commented
> @kc-leung don't know how this compares to your solution, maybe it helps: https://community.plotly.com/t/text-is-cut-off-in-plotly-horizontal-bar-chart/47233

:o nice I will give it a try thanks!

2022-09-21 13:45 UTC, kc-leung commented
@geoerika I built pyramid-bar with a different mechanism from other plotly charts. Currently xAxis values have be to dynamically passed down by the user which is why in widget studio in the plotly file for pyramid is a bit different. I will create another PR after this and try to make it to use the same transformData logic.

2022-09-22 13:09 UTC, geoerika commented
@kc-leung the cutting issue above with large values also appears for horizontal bar charts, it's not restricted to the pyramid chart. What I say is let's take this solution, but we have to look for a better one:
<img width="717" alt="Screen Shot 2022-09-22 at 9 09 05 AM" src="https://user-images.githubusercontent.com/41120953/191755604-7c508b6c-20bc-438a-8bec-9ab5cb0cb4bb.png">

2022-09-22 13:10 UTC, geoerika approved these changes

2022-09-22 13:54 UTC, kc-leung commented
> @kc-leung the cutting issue above with large values also appears for horizontal bar charts, it's not restricted to the pyramid chart. What I say is let's take this solution, but we have to look for a better one: <img alt="Screen Shot 2022-09-22 at 9 09 05 AM" width="717" src="https://user-images.githubusercontent.com/41120953/191755604-7c508b6c-20bc-438a-8bec-9ab5cb0cb4bb.png">

I will find a way to shortened format for long numbers

2022-09-22 13:55 UTC, merged

2022-09-22 13:57 UTC, geoerika commented
@kc-leung it's not about formatting, that we already have. It's about the chart handling all cases correctly, which it is not doing at the moment.

2022-09-22 14:05 UTC, kc-leung commented
> @kc-leung it's not about formatting, that we already have. It's about the chart handling all cases correctly, which it is not doing at the moment.
the text displayed outside of the graph in plotly aren't taken as a block/inline element. They are like in position: absolute or floating which it won't expand the view box of the graph. The current solution is using range getting the max value rounding it up and multiplying it 1.1 so the range view is higher

2022-09-22 15:45 UTC, geoerika commented
Oh, I see, that's what you mean by formatting...