[G2M] legend - change legend styling
EQWorks/chart-system pull request #226
Opened 2023-02-10 17:45 UTC by kc-leung

https://www.notion.so/eqproduct/Adjust-Legend-styling-using-Figma-design-in-Plotly-to-manage-better-fit-in-the-widgets-d00aeb7fc4d840099557d06b09c011b7?pvs=4

2023-02-14 18:18 UTC, geoerika commented
@kc-leung I tested these changes and we almost solved the problem with the legend. There is only one Pie chart that cannot fit 3 rows of items in the Legend. Perhaps you can adjust the max container of it so it all fits?
<img width="507" alt="Screen Shot 2023-02-14 at 1 17 00 PM" src="https://user-images.githubusercontent.com/41120953/218823479-05a4245f-d20a-4ab0-9581-a4b82c305570.png">

2023-02-14 18:19 UTC, geoerika commented
@kc-leung the spacing above the Legend in especially the bar charts still is an issue (too large).

2023-02-14 18:20 UTC, geoerika requested changes
See my comments.

2023-02-14 19:10 UTC, kc-leung commented
> @kc-leung I tested these changes and we almost solved the problem with the legend. There is only one Pie chart that cannot fit 3 rows of items in the Legend. Perhaps you can adjust the max container of it so it all fits? <img alt="Screen Shot 2023-02-14 at 1 17 00 PM" width="507" src="https://user-images.githubusercontent.com/41120953/218823479-05a4245f-d20a-4ab0-9581-a4b82c305570.png">

I will see what size will match and let you know once it is ready

2023-02-15 13:47 UTC, geoerika commented
@kc-leung please remove all custom styling depending on the type of the chart, keep just the general adjustments in the legend. 

1. Then let's try increasing the space the Legend can get by increasing all % in this block from 20 to 30%.
https://github.com/EQWorks/chart-system/blob/97ba624f44276b8057ced3695289d6eedcdc5425/src/components/plotly/shared/styles/index.js#L20

2. Also, I investigated last night and I believe we are rendering an empty div right underneath the chart and that is the problem with the space not shrinking, because I see an empty div with padding & margin and x and y params. Could you please not render this if title or subtitles are empty strings:

https://github.com/EQWorks/chart-system/blob/97ba624f44276b8057ced3695289d6eedcdc5425/src/components/plotly/shared/custom-plot.js#L165

<img width="1161" alt="Screen Shot 2023-02-15 at 8 44 47 AM" src="https://user-images.githubusercontent.com/41120953/219044604-46425a84-c2fc-4d30-9820-d290fef72ffd.png">

2023-02-15 20:26 UTC, Hamaad102 approved these changes

2023-02-15 21:00 UTC, vlatawiec approved these changes

2023-02-15 21:15 UTC, merged